security :
    user:
      name: user
      password: d4be46ce-ab1f-43ea-ba78-0ba16b49051c

logging:
  level:
    org:
      springframework:
        web : DEBUG

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eurekaserver:8761/eureka/