server:
  port: 8761

eureka:
  client:
    register-with-eureka: false # tells spring boot service not to register with a Eureka Service because this is eureka service
    fetch-registry: false

  server:
    wait-time-in-ms-when-sync-empty: 5
