server:
  port: 8888
spring:
  cloud:
    config:
      server:
        encrypt.enabled: false
        git:
          uri: https://github.com/maiorovi/config-repo
          searchPaths: licensingservice,organizationservice
          username: native-cloud-apps
          password: 0ffended
      discovery:
        enabled: true